services:
  voicevox-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - VOICEVOX_ENGINE_URL=http://voicevox-engine:50021
    depends_on:
      - voicevox-engine
    restart: unless-stopped

  voicevox-engine:
    image: voicevox/voicevox_engine:cpu-latest
    restart: unless-stopped
